config/routes.rb
Rails.application.routes.draw do
  resources :vehicles
  resources :dealerships
  resources :sales
  devise_for :users, controllers: {
    registrations: "users/registrations"
  } 
  post "/purchase/:vehicle_id", to: 'sales#purchase', as: 'purchase_vehicle'
  #get 'dashboard/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "dashboard#index"
end

app/models/dealership.rb
class Dealership < ApplicationRecord
    has_and_belongs_to_many :vehicles
    validates :name, :address, presence: true
    validates :phone, presence: true, length: { is: 10 }
end

app/controllers/dealerships_controller.rb
class DealershipsController < ApplicationController
  load_and_authorize_resource
  before_action :set_dealership, only: %i[ show edit update destroy ]

  # GET /dealerships or /dealerships.json
  def index
    @dealerships = Dealership.all
  end

  # GET /dealerships/1 or /dealerships/1.json
  def show
  end

  # GET /dealerships/new
  def new
    @dealership = Dealership.new
  end

  # GET /dealerships/1/edit
  def edit
  end

  # POST /dealerships or /dealerships.json
  def create
    @dealership = Dealership.new(dealership_params)

    respond_to do |format|
      if @dealership.save
        format.html { redirect_to dealership_url(@dealership), notice: "Dealership was successfully created." }
        format.json { render :show, status: :created, location: @dealership }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dealership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dealerships/1 or /dealerships/1.json
  def update
    respond_to do |format|
      if @dealership.update(dealership_params)
        format.html { redirect_to dealership_url(@dealership), notice: "Dealership was successfully updated." }
        format.json { render :show, status: :ok, location: @dealership }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dealership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dealerships/1 or /dealerships/1.json
  def destroy
    @dealership.destroy

    respond_to do |format|
      format.html { redirect_to dealerships_url, notice: "Dealership was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dealership
      @dealership = Dealership.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dealership_params
      params.require(:dealership).permit(:name, :address, :phone)
    end
end

app/helpers/dealerships_helper.rb
module DealershipsHelper
end

app/views/dealerships/_dealership.html.erb
<div id="<%= dom_id dealership %>">
  <p>
    <strong>Name:</strong>
    <%= dealership.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= dealership.address %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= dealership.phone %>
  </p>

</div>

app/views/dealerships/_form.html.erb
<%= form_with(model: dealership) do |form| %>
  <% if dealership.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(dealership.errors.count, "error") %> prohibited this dealership from being saved:</h2>

      <ul>
        <% dealership.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name,  class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div>
    <%= form.label :address,  class: "form-label" %>
    <%= form.text_field :address, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :phone,  class: "form-label" %>
    <%= form.number_field :phone, class: "form-control" %>
  </div>

  <div>
    <%= form.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/dealerships/edit.html.erb
<h1>Editing dealership</h1>

<%= render "form", dealership: @dealership %>

<br>

<div>
  <%= link_to "Show this dealership", @dealership %> |
  <%= link_to "Back to dealerships", dealerships_path %>
</div>

app/views/dealerships/index.html.erb
<div id="dealerships" class="container">
<h1>Dealerships</h1>
<%= link_to "New dealership", new_dealership_path, class: "btn btn-primary" %>
  <% @dealerships.each do |dealership| %>
    <%= render dealership %>
    <p>
      <%= link_to "Show this dealership", dealership, class:"btn btn-info" %>
    </p>
  <% end %>
</div>

app/views/dealerships/new.html.erb
<div class="container">
<h1>New dealership</h1>

<%= render "form", dealership: @dealership %>

<br>

<div>
  <%= link_to "Back to dealerships", dealerships_path, class: "btn btn-primary" %>
</div>

</div>

app/views/dealerships/show.html.erb
<div class="container">

  <%= render @dealership %>

    <div>
      <%= link_to "Edit this dealership" , edit_dealership_path(@dealership), class: "btn btn-primary" %> |
        <%= link_to "Back to dealerships" , dealerships_path, class: "btn btn-secondary" %>

          <%= button_to "Destroy this dealership" , @dealership, method: :delete, class: "btn btn-danger mt-2" %>
    </div>

</div>