config/routes.rb
Rails.application.routes.draw do
  resources :vehicles
  resources :dealerships
  resources :sales
  devise_for :users, controllers: {
    registrations: "users/registrations"
  } 
  post "/purchase/:vehicle_id", to: 'sales#purchase', as: 'purchase_vehicle'
  #get 'dashboard/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "dashboard#index"
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
	<div class="container-fluid">
		<a class="navbar-brand" href="<%= root_path %>">Inventarios</a>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
			aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarNav">
			<ul class="navbar-nav">
				<li class="nav-item">
					<a class="nav-link active" aria-current="page" href="<%= vehicles_path %>">Vehículos</a>
				</li>
				<% if current_user.admin? %>
					
				
				<li class="nav-item">
					<a class="nav-link" href="<%= dealerships_path %>">Consecionarias</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="<%= sales_path %>">Ventas</a>
				</li>
				<% end %>
				<% if user_signed_in? %>
				<li class="nav-item">
					<%= button_to 'Cerrar sesión' , destroy_user_session_path, method: :delete, class:"nav-item btn btn-danger" %>
				</li>
				<% end %>
			</ul>
		</div>
	</div>
</nav>