config/routes.rb
Rails.application.routes.draw do
  resources :vehicles
  resources :dealerships
  resources :sales
  devise_for :users, controllers: {
    registrations: "users/registrations"
  } 
  post "/purchase/:vehicle_id", to: 'sales#purchase', as: 'purchase_vehicle'
  #get 'dashboard/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "dashboard#index"
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
    has_and_belongs_to_many :dealerships
    has_many :sales

    enum condition: { new_vehicle: 'new', used_vehicle: 'used' }

    validates :make, :model, :price, :stock, :dealership_ids, presence: true
    validates :price, numericality: { greater_than_or_equal_to: 10000 }

    def self.depreciate_prices
        where("created_at < ?", 30.days.ago).find_each do |vehicle|
          vehicle.update(price: vehicle.price * 0.98)
        end
    end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  load_and_authorize_resource
  before_action :set_vehicle, only: %i[ show edit update destroy ]

  # GET /vehicles or /vehicles.json
  def index
    if params[:dealership_id].present?
      @vehicles = Vehicle.joins(:dealerships_vehicles).where(dealerships_vehicles: { dealership_id: params[:dealership_id] })
    else
      @vehicles = Vehicle.all
    end
  end
  

  # GET /vehicles/1 or /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles or /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)
    @vehicle.dealerships.replace(Dealership.where(id: params[:vehicle][:dealership_ids]))
    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to vehicle_url(@vehicle), notice: "Vehicle was successfully created." }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1 or /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to vehicle_url(@vehicle), notice: "Vehicle was successfully updated." }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1 or /vehicles/1.json
  def destroy
    @vehicle.destroy

    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: "Vehicle was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vehicle_params
      params.require(:vehicle).permit(:make, :model, :year, :vehicle_type, :price, :stock, :condition, dealership_ids: [])
    end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<%= form_with(model: vehicle) do |form| %>
  <% if vehicle.errors.any? %>
    <div style="color: red">
      <h2>
        <%= pluralize(vehicle.errors.count, "error" ) %> prohibited this vehicle from being saved:
      </h2>

      <ul>
        <% vehicle.errors.each do |error| %>
          <li>
            <%= error.full_message %>
          </li>
          <% end %>
      </ul>
    </div>
    <% end %>

      <div class="mb-3">
        <%= form.label :make, class: "form-label" %>
          <%= form.text_field :make, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :model, class: "form-label" %>
          <%= form.text_field :model, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :year, class: "form-label" %>
          <%= form.number_field :year, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :type, class: "form-label" %>
          <%= form.text_field :vehicle_type, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :price, class: "form-label" %>
          <%= form.number_field :price, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :stock, class: "form-label" %>
          <%= form.number_field :stock, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :condition, class: "form-label" %>
          <%= form.select :condition, Vehicle.conditions.keys.map { |c| [c.humanize, c] }, {}, class: "form-control" %>
      </div>


      <div class="mb-3">
        <%= form.label :dealership_ids, "Concesionarias" %><br>
          <% Dealership.all.each do |dealership| %>
            <%= check_box_tag "vehicle[dealership_ids][]" , dealership.id, @vehicle.dealerships.include?(dealership) %>
              <%= label_tag "vehicle_dealership_ids_#{dealership.id}" , dealership.name %><br>
                <% end %>
      </div>

      <div>
        <%= form.submit class: "btn btn-success" %>
      </div>
      <% end %>

app/views/vehicles/_vehicle.html.erb
<div id="<%= dom_id vehicle %>" class="col-3">
  <p>
    <strong>Make:</strong>
    <%= vehicle.make %>
  </p>

  <p>
    <strong>Model:</strong>
    <%= vehicle.model %>
  </p>

  <p>
    <strong>Year:</strong>
    <%= vehicle.year %>
  </p>

  <p>
    <strong>Type:</strong>
    <%= vehicle.vehicle_type %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= vehicle.price %>
  </p>

  <p>
    <strong>Stock:</strong>
    <%= vehicle.stock %>
  </p>

  <p>
    <strong>Condition:</strong>
    <%= vehicle.condition.humanize %>
  </p>
    <p>
      <%= link_to "Show this vehicle", vehicle, class: "btn btn-primary" %>
    </p>
</div>

app/views/vehicles/edit.html.erb
<h1>Editing vehicle</h1>

<%= render "form", vehicle: @vehicle %>

<br>

<div>
  <%= link_to "Show this vehicle", @vehicle %> |
  <%= link_to "Back to vehicles", vehicles_path %>
</div>

app/views/vehicles/index.html.erb
<div class="container text-center">

<h1>Vehicles</h1>
<% if current_user.admin? %>
<%= link_to "New vehicle", new_vehicle_path, class: "btn btn-primary" %>
<% else %>
  <%= form_tag vehicles_path, method: :get do %>
  <%= select_tag :dealership_id, options_for_select(Dealership.all.map { |d| [d.name, d.id] }), prompt: "Seleccionar concesionaria" %>
  <%= submit_tag "Filtrar" %>
<% end %>
<% end %>


<div id="vehicles" class="row align-items-start">

  <% @vehicles.each do |vehicle| %>
    <%= render vehicle %>
  <% end %>

</div>


</div>

app/views/vehicles/new.html.erb
<div class="container">
<h1>New vehicle</h1>

<%= render "form", vehicle: @vehicle %>

<br>

<div>
  <%= link_to "Back to vehicles", vehicles_path, class: "btn btn-primary" %>
</div>
</div>

app/views/vehicles/show.html.erb
<div class="container">
  <div class="card">
    <div class="card-header">
      <h3 class="text-center">Vehicle: <%= @vehicle.make %></h3>
    </div>
    <div class="card-body">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <strong>Make:</strong>
          <%= @vehicle.make %>
        </li>
        <li class="list-group-item">
          <strong>Model:</strong>
          <%= @vehicle.model %>
        </li>
        <li class="list-group-item">
          <strong>Year:</strong>
          <%= @vehicle.year %>
        </li>
        <li class="list-group-item">
          <strong>Type:</strong>
          <%= @vehicle.vehicle_type %>
        </li>
        <li class="list-group-item">
          <strong>Type:</strong>
          <%= @vehicle.vehicle_type %>
        </li>
        <li class="list-group-item">
          <strong>Price:</strong>
          <%= @vehicle.price %>
        </li>
        <li class="list-group-item">
          <strong>Stock:</strong>
          <%= @vehicle.stock %>
        </li>
        <li class="list-group-item">
          <strong>Condition:</strong>
          <%= @vehicle.condition.humanize %>
        </li>
      </ul>
  </div>

  <div>
    <%= link_to "Back to vehicles" , vehicles_path, class:"btn btn-secondary" %> |

      <% if current_user.admin? %>
        <%= link_to "Edit this vehicle" , edit_vehicle_path(@vehicle),  class:"btn btn-primary" %> 
          <%= button_to "Destroy this vehicle" , @vehicle, method: :delete,  class:"btn btn-danger" %>
      <%  else  %>
      <%= button_to "Buy", purchase_vehicle_path(@vehicle), method: :post, class: "btn btn-success" %>
      <% end %>
  </div>

</div>